{
  "swagger": "2.0",
  "info": {
    "title": "Organization API",
    "version": "version not set"
  },
  "tags": [
    {
      "name": "OrgAPI",
      "description": "Provides API to manage the organizations available for your Percona services."
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/orgs": {
      "post": {
        "summary": "Create organization",
        "description": "Create a new organization with the given name and add the user as organization administrator. If the email belongs to an existing Percona customer, the new organization is automatically linked to their existing organization on Percona Customer Portal.",
        "operationId": "OrgAPI_CreateOrganization",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1CreateOrganizationResponse"
            },
            "examples": {
              "application/json": {
                "org": {
                  "id": "b0e2e3d6-b909-43f0-9871-f9bcbf4a02ef",
                  "name": "Percona SANDBOX",
                  "created_at": "2021-12-10T07:41:08.925367Z",
                  "updated_at": "2021-12-10T07:41:08.925367Z"
                }
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1CreateOrganizationRequest"
            }
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/company:search": {
      "post": {
        "summary": "Search organization tickets",
        "description": "Search by Percona customer email. This method only returns information if the user email is linked to an existing Percona Customer Portal account.",
        "operationId": "OrgAPI_SearchUserCompany",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1SearchUserCompanyResponse"
            },
            "examples": {
              "application/json": {
                "name": "Percona SANDBOX"
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/inventory": {
      "post": {
        "summary": "Connect PMM Server",
        "description": "Connect PMM Server to organization.",
        "operationId": "OrgAPI_ConnectPMM",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1ConnectPMMResponse"
            },
            "examples": {
              "application/json": {
                "sso_details": {
                  "grafana_client_id": "bdheuwort62379fwbeui",
                  "pmm_managed_client_id": "bdheuwort62379fwbeui",
                  "pmm_managed_client_secret": "bvhjrfbwjrkfnbbrjeknfberjk",
                  "issuer_url": "https://id.percona.com/oauth2/bfewhukfgweyurgwyu/v1",
                  "scope": "percona"
                },
                "org_id": "b0e2e3d6-b909-43f0-9871-f9bcbf4a02ef"
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1ConnectPMMRequest"
            }
          }
        ],
        "tags": [
          "Inventory Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/inventory/{pmmServerId}:disconnect": {
      "post": {
        "summary": "Disconnect PMM Server",
        "description": "Disconnect PMM Server from organization.",
        "operationId": "OrgAPI_DisconnectPMM",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "properties": {}
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "pmmServerId",
            "description": "PMM server ID.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Inventory Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/inventory:connect": {
      "post": {
        "summary": "Connect PMM Server",
        "description": "Connect PMM Server to organization.",
        "operationId": "OrgAPI_ConnectPMM2",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1ConnectPMMResponse"
            },
            "examples": {
              "application/json": {
                "sso_details": {
                  "grafana_client_id": "bdheuwort62379fwbeui",
                  "pmm_managed_client_id": "bdheuwort62379fwbeui",
                  "pmm_managed_client_secret": "bvhjrfbwjrkfnbbrjeknfberjk",
                  "issuer_url": "https://id.percona.com/oauth2/bfewhukfgweyurgwyu/v1",
                  "scope": "percona"
                },
                "org_id": "b0e2e3d6-b909-43f0-9871-f9bcbf4a02ef"
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1ConnectPMMRequest"
            }
          }
        ],
        "tags": [
          "Inventory Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}": {
      "get": {
        "summary": "Get organization info",
        "description": "Get organization info by ID.",
        "operationId": "OrgAPI_GetOrganization",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1GetOrganizationResponse"
            },
            "examples": {
              "application/json": {
                "org": {
                  "id": "b0e2e3d6-b909-43f0-9871-f9bcbf4a02ef",
                  "name": "Percona SANDBOX",
                  "created_at": "2021-12-10T07:41:08.925367Z",
                  "updated_at": "2021-12-10T07:41:08.925367Z"
                }
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      },
      "delete": {
        "summary": "Delete organization",
        "description": "Delete organization by ID.",
        "operationId": "OrgAPI_DeleteOrganization",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1DeleteOrganizationResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/entitlements:search": {
      "post": {
        "summary": "Search organization entitlements",
        "description": "Search organization entitlements. This method only returns information if the organization is linked to an existing Percona Customer Portal account.",
        "operationId": "OrgAPI_SearchOrganizationEntitlements",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1SearchOrganizationEntitlementsResponse"
            },
            "examples": {
              "application/json": {
                "entitlements": [
                  {
                    "number": "ENTLMT0001026",
                    "name": "Unmeasured MySQL Support - Premium - ENTLMT0001026",
                    "summary": "3 MySQL Servers",
                    "tier": "",
                    "total_units": "3",
                    "unlimited_units": false,
                    "support_level": "",
                    "software_families": [
                      "MySQL"
                    ],
                    "start_date": "2019-10-28T00:00:00Z",
                    "end_date": "2021-07-01T00:00:00Z",
                    "platform": {
                      "security_advisor": "",
                      "config_advisor": ""
                    }
                  }
                ]
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/inventory:search": {
      "post": {
        "summary": "Search connected PMM Servers",
        "description": "Search all PMM servers connected to an organization.",
        "operationId": "OrgAPI_SearchInventory",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1SearchInventoryResponse"
            },
            "examples": {
              "application/json": {
                "inventory": [
                  {
                    "pmm_server_id": "ded64cd9-2f9e-78ac-247a-d98ad1f95e85",
                    "pmm_server_name": "Small Rubber Shoes",
                    "pmm_server_url": "https://laverna.biz"
                  }
                ]
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Inventory Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/members": {
      "post": {
        "summary": "Invite organization member",
        "description": "Invite users to the organization and specify their member roles.",
        "operationId": "OrgAPI_InviteMember",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1InviteMemberResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal organization ID to which to invite the user to.",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string",
                  "description": "Percona Portal username to invite to the Organziation."
                },
                "role": {
                  "type": "string",
                  "description": "Percona Portal organization role to be granted to the invited user."
                }
              }
            }
          }
        ],
        "tags": [
          "Member Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/members/{memberId}": {
      "delete": {
        "summary": "Delete organization member",
        "description": "Delete member from organization.",
        "operationId": "OrgAPI_DeleteMember",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "properties": {}
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "memberId",
            "description": "Percona Portal Member ID.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Member Management"
        ],
        "produces": [
          "application/json"
        ]
      },
      "put": {
        "summary": "Update organization member",
        "description": "Update organization member's role.",
        "operationId": "OrgAPI_UpdateMember",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1UpdateMemberResponse"
            },
            "examples": {
              "application/json": {
                "member": {
                  "member_id": "1a8e7b33-59bc-42a5-b1a8-2180576badde",
                  "username": "admin@org.com",
                  "first_name": "First Name",
                  "last_name": "Last Name",
                  "role": "Admin",
                  "status": "ACTIVE"
                }
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "memberId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "role": {
                  "type": "string",
                  "description": "Organization member role."
                }
              }
            }
          }
        ],
        "tags": [
          "Member Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/members:bulk": {
      "post": {
        "summary": "Bulk invite organization members",
        "description": "Invite users to the organization and specify their member roles.",
        "operationId": "OrgAPI_BulkInviteMembers",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1BulkInviteMembersResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID to which to invite users to.",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "users": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/v1OrganizationInvitee"
                  },
                  "description": "Array of users to invite to the Organization."
                }
              }
            }
          }
        ],
        "tags": [
          "Member Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/members:search": {
      "post": {
        "summary": "Search organization members",
        "description": "Search organization members.",
        "operationId": "OrgAPI_SearchMembers",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1SearchMembersResponse"
            },
            "examples": {
              "application/json": {
                "members": [
                  {
                    "member_id": "c1ede3d6-ce34-1234-9871-7af2bf4a02ef",
                    "username": "test@org.com",
                    "first_name": "First Name",
                    "last_name": "Last Name",
                    "role": "OrgAdmin",
                    "status": "ACTIVE"
                  }
                ]
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "user": {
                  "$ref": "#/definitions/SearchMembersRequestUserFilter"
                }
              }
            }
          }
        ],
        "tags": [
          "Member Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{orgId}/tickets:search": {
      "post": {
        "summary": "Search organization tickets",
        "description": "Search organization tickets. This method only returns information if the organization is linked to an existing Percona Customer Portal account.",
        "operationId": "OrgAPI_SearchOrganizationTickets",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1SearchOrganizationTicketsResponse"
            },
            "examples": {
              "application/json": {
                "tickets": [
                  {
                    "number": "TIME0001218",
                    "short_description": "Percona SANDBOX Percona Managed Database Services for PostgreSQL - ENTLMT0003359",
                    "priority": "P3 - Normal",
                    "state": "Open",
                    "create_time": "2022-01-14T20:53:22Z",
                    "department": "Managed Services",
                    "requester": "",
                    "task_type": "Internal Tracking",
                    "url": "https://perconadev.service-now.com/percona?id=percona_ticket\u0026table=u_internal_tracking\u0026sys_id=b2a175a587098d508d75c9d8cebb35a8"
                  }
                ]
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "orgId",
            "description": "Percona Portal Organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs/{organization.id}": {
      "put": {
        "summary": "Update organization",
        "description": "Update organization info.",
        "operationId": "OrgAPI_UpdateOrganization",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1UpdateOrganizationResponse"
            },
            "examples": {
              "application/json": {
                "org": {
                  "id": "b0e2e3d6-b909-43f0-9871-f9bcbf4a02ef",
                  "name": "Percona SANDBOX",
                  "created_at": "2021-12-10T07:41:08.925367Z",
                  "updated_at": "2021-12-10T07:41:08.925367Z"
                }
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "organization.id",
            "description": "Percona Portal organization ID.",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "organization",
            "description": "Percona Portal Organization",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Percona Portal organization name."
                },
                "createdAt": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Timestamp when the organization was created."
                },
                "updatedAt": {
                  "type": "string",
                  "format": "date-time",
                  "description": "Timestamp when the organization was last updated."
                },
                "tier": {
                  "$ref": "#/definitions/v1Tier",
                  "description": "Tier of the client linked to the organization."
                }
              },
              "title": "Percona Portal Organization"
            }
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    },
    "/v1/orgs:search": {
      "post": {
        "summary": "Search organizations",
        "description": "Search for organizations that the user is a member of.",
        "operationId": "OrgAPI_SearchOrganizations",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v1SearchOrganizationsResponse"
            },
            "examples": {
              "application/json": {
                "orgs": [
                  {
                    "id": "b0e2e3d6-b909-43f0-9871-f9bcbf4a02ef",
                    "name": "Percona SANDBOX",
                    "created_at": "2021-12-10T07:41:08.925367Z",
                    "updated_at": "2021-12-10T07:41:08.925367Z"
                  }
                ]
              }
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1SearchOrganizationsRequest"
            }
          }
        ],
        "tags": [
          "Organization Management"
        ],
        "produces": [
          "application/json"
        ]
      }
    }
  },
  "definitions": {
    "ContactsCustomerSuccess": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      }
    },
    "OrganizationEntitlementPlatform": {
      "type": "object",
      "properties": {
        "securityAdvisor": {
          "type": "string",
          "description": "Flag indicates that security advisors are covered by this entitlement."
        },
        "configAdvisor": {
          "type": "string",
          "description": "Flag indicates that config advisors are covered by this entitlement."
        }
      }
    },
    "SearchMembersRequestUserFilter": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "description": "Organization member username."
        }
      },
      "description": "Optional filter that PMM uses to get information about the current user."
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    },
    "v1BulkInviteMembersResponse": {
      "type": "object",
      "properties": {
        "statuses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1InviteStatus"
          }
        }
      }
    },
    "v1ConnectPMMRequest": {
      "type": "object",
      "properties": {
        "pmmServerId": {
          "type": "string",
          "description": "PMM Server unique ID."
        },
        "pmmServerName": {
          "type": "string",
          "description": "User-defined human-readable PMM Server name."
        },
        "pmmServerUrl": {
          "type": "string",
          "description": "PMM Server address accessible to users."
        },
        "pmmServerOauthCallbackUrl": {
          "type": "string",
          "description": "URL for oauth callback."
        }
      }
    },
    "v1ConnectPMMResponse": {
      "type": "object",
      "properties": {
        "ssoDetails": {
          "$ref": "#/definitions/v1PMMServerSSODetails"
        },
        "orgId": {
          "type": "string"
        }
      }
    },
    "v1Contacts": {
      "type": "object",
      "properties": {
        "customerSuccess": {
          "$ref": "#/definitions/ContactsCustomerSuccess",
          "description": "Contact information of the Customer Success employee assigned to a customer's account."
        },
        "newTicketUrl": {
          "type": "string",
          "description": "Ticket URL."
        }
      }
    },
    "v1CreateOrganizationRequest": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Organization name.",
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "name"
      ]
    },
    "v1CreateOrganizationResponse": {
      "type": "object",
      "properties": {
        "org": {
          "$ref": "#/definitions/v1Organization"
        }
      }
    },
    "v1DeleteOrganizationResponse": {
      "type": "object"
    },
    "v1GetOrganizationResponse": {
      "type": "object",
      "properties": {
        "org": {
          "$ref": "#/definitions/v1Organization"
        },
        "contacts": {
          "$ref": "#/definitions/v1Contacts"
        }
      }
    },
    "v1Inventory": {
      "type": "object",
      "properties": {
        "pmmServerId": {
          "type": "string",
          "title": "PMM Server ID"
        },
        "pmmServerName": {
          "type": "string",
          "description": "User-defined, human-readable PMM Server name."
        },
        "pmmServerUrl": {
          "type": "string",
          "description": "PMM Server address accessible to the users."
        }
      }
    },
    "v1InviteMemberResponse": {
      "type": "object"
    },
    "v1InviteStatus": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "title": "Percona Portal username that was attempted to invite to the Organization"
        },
        "error": {
          "type": "string",
          "title": "Error if an attempt failed"
        }
      }
    },
    "v1Organization": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Percona Portal organization ID."
        },
        "name": {
          "type": "string",
          "description": "Percona Portal organization name."
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Timestamp when the organization was created."
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Timestamp when the organization was last updated."
        },
        "tier": {
          "$ref": "#/definitions/v1Tier",
          "description": "Tier of the client linked to the organization."
        }
      }
    },
    "v1OrganizationEntitlement": {
      "type": "object",
      "properties": {
        "number": {
          "type": "string",
          "description": "Entitlement number."
        },
        "name": {
          "type": "string",
          "description": "Entitlement name."
        },
        "summary": {
          "type": "string",
          "description": "Entitlement short summary."
        },
        "tier": {
          "type": "string",
          "description": "Entitlement tier."
        },
        "totalUnits": {
          "type": "string",
          "description": "Total units covered by this entitlement."
        },
        "unlimitedUnits": {
          "type": "boolean",
          "description": "Flag indicates that unlimited units are covered."
        },
        "supportLevel": {
          "type": "string",
          "description": "Support level covered by this entitlement."
        },
        "softwareFamilies": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Percona product families covered by this entitlement."
        },
        "startDate": {
          "type": "string",
          "format": "date-time",
          "description": "Entitlement start data.\nNote: only date is used here but not time."
        },
        "endDate": {
          "type": "string",
          "format": "date-time",
          "description": "Entitlement end date.\nNote: only date is used here but not time."
        },
        "platform": {
          "$ref": "#/definitions/OrganizationEntitlementPlatform",
          "description": "Platform-specific options covered by this entitlement."
        }
      },
      "description": "Contains information about the organization entitlement."
    },
    "v1OrganizationInvitee": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "description": "Percona Portal username to invite to the Organziation."
        },
        "role": {
          "type": "string",
          "description": "Percona Portal Organization Role to be granted to invited user."
        }
      }
    },
    "v1OrganizationMember": {
      "type": "object",
      "properties": {
        "memberId": {
          "type": "string",
          "description": "Percona Portal member UUID."
        },
        "username": {
          "type": "string",
          "description": "Percona Portal username of the organization member."
        },
        "firstName": {
          "type": "string",
          "description": "First name of the organization member."
        },
        "lastName": {
          "type": "string",
          "description": "Last name of the organization member."
        },
        "role": {
          "type": "string",
          "description": "Percona Portal organization role of the member."
        },
        "status": {
          "type": "string",
          "description": "Okta Account Status of the organization member."
        }
      }
    },
    "v1OrganizationTicket": {
      "type": "object",
      "properties": {
        "number": {
          "type": "string",
          "description": "Ticket number."
        },
        "shortDescription": {
          "type": "string",
          "description": "Ticket short description."
        },
        "priority": {
          "type": "string",
          "description": "Ticket priority."
        },
        "state": {
          "type": "string",
          "description": "Ticket state."
        },
        "createTime": {
          "type": "string",
          "format": "date-time",
          "description": "Ticket creation time."
        },
        "department": {
          "type": "string",
          "description": "Department."
        },
        "requester": {
          "type": "string",
          "description": "Ticket requester."
        },
        "taskType": {
          "type": "string",
          "description": "Task type."
        },
        "url": {
          "type": "string",
          "description": "Ticket URL."
        }
      },
      "description": "Contains information about the ticket."
    },
    "v1PMMServerSSODetails": {
      "type": "object",
      "properties": {
        "clientId": {
          "type": "string"
        },
        "clientSecret": {
          "type": "string"
        },
        "issuerUrl": {
          "type": "string"
        },
        "scope": {
          "type": "string"
        },
        "grafanaClientId": {
          "type": "string"
        },
        "pmmManagedClientId": {
          "type": "string"
        },
        "pmmManagedClientSecret": {
          "type": "string"
        }
      }
    },
    "v1SearchInventoryResponse": {
      "type": "object",
      "properties": {
        "inventory": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1Inventory"
          }
        }
      }
    },
    "v1SearchMembersResponse": {
      "type": "object",
      "properties": {
        "members": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1OrganizationMember"
          }
        }
      }
    },
    "v1SearchOrganizationEntitlementsResponse": {
      "type": "object",
      "properties": {
        "entitlements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1OrganizationEntitlement"
          }
        }
      }
    },
    "v1SearchOrganizationTicketsResponse": {
      "type": "object",
      "properties": {
        "tickets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1OrganizationTicket"
          },
          "description": "Organization tickets matching the request."
        }
      }
    },
    "v1SearchOrganizationsRequest": {
      "type": "object"
    },
    "v1SearchOrganizationsResponse": {
      "type": "object",
      "properties": {
        "orgs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/v1Organization"
          }
        }
      }
    },
    "v1SearchUserCompanyResponse": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Percona Customer name."
        }
      }
    },
    "v1Tier": {
      "type": "string",
      "enum": [
        "INVALID",
        "REGISTERED",
        "PAID"
      ],
      "default": "INVALID",
      "description": "DistributionMethod represents PMM Server distribution method.\n\n - INVALID: INVALID used for unsupported values.\n - REGISTERED: REGISTERED represents account that is registered on Portal.\n - PAID: PAID represents paid account."
    },
    "v1UpdateMemberResponse": {
      "type": "object",
      "properties": {
        "member": {
          "$ref": "#/definitions/v1OrganizationMember"
        }
      }
    },
    "v1UpdateOrganizationResponse": {
      "type": "object",
      "properties": {
        "org": {
          "$ref": "#/definitions/v1Organization"
        }
      }
    }
  },
  "x-readme": {
    "samples-languages": [
      "curl",
      "go",
      "node",
      "python"
    ]
  }
}
